workflows:
  version-boa-android:
    name: Version Boa Android
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      node: v14.19.3
      java: 11.0.17
    scripts:
      - name: yarn install
        script: |
          yarn install
      - name: Build boa version
        working_directory: whitelabel/android/brands/boa
        script: yarn install && node index.js
      - name: Create APK
        script: |
          cd android && ./gradlew assembleRelease
    artifacts:
    - android/app/build/outputs/**/*.apk


  version-plurix-android:
    name: Version Plurix Android
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      node: v14.19.3
      java: 11.0.17
    scripts:
      - name: yarn install
        script: |
          yarn install
      - name: Build superpao version
        working_directory: whitelabel/android/brands/plurix
        script: yarn install && node index.js
      - name: Create APK
        script: |
          cd android && ./gradlew assembleRelease
    artifacts:
    - android/app/build/outputs/**/*.apk

  version-superpao-android:
    name: Version Superpao Android
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      node: v14.19.3
      java: 11.0.17
    scripts:
      - name: yarn install
        script: |
          yarn install
      - name: Build superpao version
        working_directory: whitelabel/android/brands/superpao
        script: yarn install && node index.js
      - name: Create APK
        script: |
          cd android && ./gradlew assembleRelease
    artifacts:
    - android/app/build/outputs/**/*.apk
