workflows:
  version-boa-android:
    name: Version Boa Android
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      node: v14.19.3
      java: 11.0.17
    scripts:
      - name: Empty
        script: echo 'waiting for whitelabel'

  version-plurix-android:
    name: Version Plurix Android
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      node: v14.19.3
      java: 11.0.17
    scripts:
      - name: Empty
        script: echo 'waiting for whitelabel'

  version-superpao-android:
    name: Version Superpao Android
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      node: v14.19.3
      java: 11.0.17
    scripts:
      - name: Build Android
        working_directory: whitelabel/android/brands/superpao
        script: pwd
      - name: yarn install
        script: |
          yarn install
      - name: Create APK
        script: |
          cd android && ./gradlew assembleRelease
    artifacts:
    - android/app/build/outputs/**/*.apk
